CREATE TABLE Clubs (
    Club_name VARCHAR(255) NOT NULL,
    Abv VARCHAR(3) NOT NULL,
    Hex_code VARCHAR(7) NOT NULL,
    Logo_link VARCHAR(255) NOT NULL,
    PRIMARY KEY (abv)
);

CREATE TABLE Results (
    Division VARCHAR(255) NOT NULL,
    Date DATE NOT NULL,
    Time TIME NOT NULL,
    HomeTeam VARCHAR(255) NOT NULL,
    AwayTeam VARCHAR(255) NOT NULL,
    FTHG INT NOT NULL,
    FTAG INT NOT NULL,
    FTR CHAR(1) NOT NULL,
    HTHG INT NOT NULL,
    HTAG INT NOT NULL,
    HTR CHAR(1) NOT NULL,
    Referee VARCHAR(255) NOT NULL,
    HS INT NOT NULL,
    AWS INT NOT NULL,
    HST INT NOT NULL,
    AST INT NOT NULL,
    HF INT NOT NULL,
    AF INT NOT NULL,
    HC INT NOT NULL,
    AC INT NOT NULL,
    HY INT NOT NULL,
    AY INT NOT NULL,
    HRC INT NOT NULL,
    ARC INT NOT NULL,
    PRIMARY KEY (Date, HomeTeam, AwayTeam),
    FOREIGN KEY (HomeTeam) REFERENCES clubs(abv),
    FOREIGN KEY (AwayTeam) REFERENCES clubs(abv)
);

CREATE TABLE Players (
    Club_abv VARCHAR(3) NOT NULL,
    Id INT(11) NOT NULL AUTO_INCREMENT,
    Name VARCHAR(50) NOT NULL,
    Height INT(11) NOT NULL,
    Position VARCHAR(2) NOT NULL,
    Born DATE NOT NULL,
    PRIMARY KEY (Club_abv, Id),
    FOREIGN KEY (Club_abv) REFERENCES Clubs(Abv)
);